kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: datastream-test
  namespace: nada
  labels:
    team: nada
spec:
  image: busybox
  command:
    - /bin/sh
    - -c
    - --
    - "while true; do sleep 30; done;"
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: datastream-test
